stages:
  - docker-hub
#   - kind-cluster
#   - deploy

build-job:
  stage: docker-hub
  script:
    - ./gradlew :telegram-stock-bot:jib -PDOCKERHUB_USERNAME="$env:DOCKERHUB_USERNAME" -PDOCKERHUB_PASSWORD="$env:DOCKERHUB_PASSWORD" -PTELEGRAM_TOKEN=""$env:$TELEGRAM_TOKEN" -PTINKOFF_TOKEN="$env:$TINKOFF_TOKEN"


# create-kind-cluster:
#   stage: kind-cluster-hub
#   script:
#     - kubectl cluster-info --context kind-kind
#     - if [$message = ]
#     - kind create cluster --config=kubernetes/kind-config.yaml

# deploy-job:
#   stage: deploy
#   environment: production
#   script:
#     - echo "Deploying application..."
#     - echo "Application successfully deployed."
