stages:
  - build
  - release
  - deploy

variables:
  GIT_SSL_NO_VERIFY: 1

.build_job:
  stage: build
  only:
    - master
  allow_failure: false
  script:
    # ToDo: Как допишу тесты, добавить ещё один стейдж 'test'
    - ./gradlew :stock-app-statistic:clean build -x test -PDOCKERHUB_USERNAME="$DOCKERHUB_USERNAME" -PDOCKERHUB_PASSWORD="$DOCKERHUB_PASSWORD"
    - ./gradlew :telegram-stock-bot:clean build -x test -PDOCKERHUB_USERNAME="$DOCKERHUB_USERNAME" -PDOCKERHUB_PASSWORD="$DOCKERHUB_PASSWORD"
    - ./gradlew :tinkoff-stock-app:clean build -x test -PDOCKERHUB_USERNAME="$DOCKERHUB_USERNAME" -PDOCKERHUB_PASSWORD="$DOCKERHUB_PASSWORD"

.assemble_job:
  stage: build
  only:
    - master
  allow_failure: false
  script:
    - ./gradlew :stock-app-statistic:assemble -PDOCKERHUB_USERNAME="$DOCKERHUB_USERNAME" -PDOCKERHUB_PASSWORD="$DOCKERHUB_PASSWORD"
    - ./gradlew :telegram-stock-bot:assemble -PDOCKERHUB_USERNAME="$DOCKERHUB_USERNAME" -PDOCKERHUB_PASSWORD="$DOCKERHUB_PASSWORD"
    - ./gradlew :tinkoff-stock-app:assemble -PDOCKERHUB_USERNAME="$DOCKERHUB_USERNAME" -PDOCKERHUB_PASSWORD="$DOCKERHUB_PASSWORD"
  # ToDo: разобраться с передачей *.jar-ников в push-to-docker-hub через artifacts/cache

.push-to-docker-hub:
  stage: release
  only:
    - master
  allow_failure: false
  script:
    # jib.dependsOn(bootJar) in build.gradle
    - ./gradlew :stock-app-statistic:jib -PDOCKERHUB_USERNAME="$DOCKERHUB_USERNAME" -PDOCKERHUB_PASSWORD="$DOCKERHUB_PASSWORD"
    - ./gradlew :telegram-stock-bot:jib -PDOCKERHUB_USERNAME="$DOCKERHUB_USERNAME" -PDOCKERHUB_PASSWORD="$DOCKERHUB_PASSWORD" -PTELEGRAM_TOKEN="$TELEGRAM_TOKEN"
    - ./gradlew :tinkoff-stock-app:jib -PDOCKERHUB_USERNAME="$DOCKERHUB_USERNAME" -PDOCKERHUB_PASSWORD="$DOCKERHUB_PASSWORD" -PTINKOFF_TOKEN="$TINKOFF_TOKEN"

create-kind-cluster:
  stage: deploy
  only:
    - master
  allow_failure: false
  before_script:
    - message=$(kind get clusters)
  script:
    - |-
      if [[ $message == "kind" ]]; then
          echo "Кластер готов."
      else 
          kind create cluster --config=kubernetes/kind-config.yaml --kubeconfig $KUBECONFIG
      fi
  after_script:
    - kind get clusters

# ToDo: По хорошему нужно обновлять deployments через kubectl patch/set по id коммита,
# чтобы у каждого тэга docker-контейнера была версия с id коммита, но для демонстрации хватит.
deploy-in-kubernetes:
  stage: deploy
  only:
    - master
  before_script:
    - cd kubernetes
    # ToDo:создать отдельный namespace для проверки перед деплоем
    - check_deployment=$(kubectl get deployment telegram-stock-bot)
    - echo $check_deployment
  script:
    - echo "ALLO"
  after_script:
    # Проверка и установка INGRESS плагина (NGINX)
    - |-
      check_ing=$(kubectl get all -n ingress-nginx)
      if [[ $check_ing =~ "No resources found in ingress-nginx" ]]; then
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
      else 
          kubectl get pods 
      fi
