stages:
  - build
  - package
  - kind-cluster
  - deploy

  # ToDo: запустить gitlab-runner под текущим пользователем (не локальным). Ошибка: 1069
build:
  stage: build
  allow_failure: false
  script:
    # ToDo: как допишу тесты, добавить ещё одни стейдж 'test'
    - ./gradlew :stock-app-statistic:build -x test -PDOCKERHUB_USERNAME="$env:DOCKERHUB_USERNAME" -PDOCKERHUB_PASSWORD="$env:DOCKERHUB_PASSWORD"
    - ./gradlew :telegram-stock-bot:build -x test -PDOCKERHUB_USERNAME="$env:DOCKERHUB_USERNAME" -PDOCKERHUB_PASSWORD="$env:DOCKERHUB_PASSWORD"
    - ./gradlew :tinkoff-stock-app:build -x test -PDOCKERHUB_USERNAME="$env:DOCKERHUB_USERNAME" -PDOCKERHUB_PASSWORD="$env:DOCKERHUB_PASSWORD"

push-to-docker-hub:
  stage: package
  allow_failure: false
  script:
    - ./gradlew :stock-app-statistic:jib -x build -PDOCKERHUB_USERNAME="$env:DOCKERHUB_USERNAME" -PDOCKERHUB_PASSWORD="$env:DOCKERHUB_PASSWORD"
    - ./gradlew :telegram-stock-bot:jib -x build -PDOCKERHUB_USERNAME="$env:DOCKERHUB_USERNAME" -PDOCKERHUB_PASSWORD="$env:DOCKERHUB_PASSWORD" -PTELEGRAM_TOKEN="$env:TELEGRAM_TOKEN"
    - ./gradlew :tinkoff-stock-app:jib -x build -PDOCKERHUB_USERNAME="$env:DOCKERHUB_USERNAME" -PDOCKERHUB_PASSWORD="$env:DOCKERHUB_PASSWORD" -PTINKOFF_TOKEN="$env:TINKOFF_TOKEN"

create-kind-cluster:
  stage: kind-cluster
  allow_failure: false
  script:
    - set message (kind get clusters 2>&1)
    - get-variable message -valueOnly
    # ToDo: разобраться, почему не работает многострочный символ '>' (folded), может из-за powershell
    - if((get-variable message -valueOnly) -like 'No kind clusters found.' -Or (get-variable message -valueOnly) -like 'error*'){kind create cluster --config=kubernetes/kind-config.yaml --kubeconfig $env:KUBE_HOME/.kube/config}else{echo "Кластер готов."}
  after_script:
    - kind get clusters

# ToDo: возможно тут нужна какая-то логика на проверку изменений в конфигах,
# но для демонстрации пойдёт и такой вариант.
deploy-in-kubernetes:
  stage: deploy
  only:
    - master
  before_script:
    - cd kubernetes
    - $env:KUBECONFIG = "$env:KUBE_HOME/.kube/config"
  script:
    # Импорт общей конфигураций
    - kubectl apply -f config/stock-app-config.yaml
    # Деплой kafka + zookeeper
    - kubectl apply -f kafka/zookeeper.yaml
    - kubectl apply -f kafka/kafka.yaml
    # Деплой PostgreSQL + PostGIS
    - kubectl apply -f db/postgres-config.yaml
    - kubectl apply -f db/storage_postgres.yaml
    - kubectl apply -f db/postgres.yaml
    # Деплой микросервиса с подсчётом статистики
    - kubectl apply -f stock-app-statistic/service_stock-app-stat.yaml
    - kubectl apply -f stock-app-statistic/deploy_stock-app-stat.yaml
    # Деплой микросервиса с телеграм-ботом
    - kubectl apply -f telegram-stock-bot/service_telegram-stock-bot.yaml
    - kubectl apply -f telegram-stock-bot/deploy_telegram-stock-bot.yaml
    # Деплой микросервиса с tinkoff API
    - kubectl apply -f tinkoff-stock-app/service_tinkoff-stock-app.yaml
    - kubectl apply -f tinkoff-stock-app/ingress_tinkoff-stock-app.yaml
    - kubectl apply -f tinkoff-stock-app/deploy_tinkoff-stock-app.yaml
  after_script:
    - kubectl get po