stages:
  - build
  - release
  - deploy

variables:
  GIT_SSL_NO_VERIFY: 1

build_job:
  stage: build
  only:
    - master
  allow_failure: false
  script:
    # ToDo: Как допишу тесты, добавить ещё один стейдж 'test'
    - ./gradlew :stock-app-statistic:clean build -x test -PDOCKERHUB_USERNAME="$DOCKERHUB_USERNAME" -PDOCKERHUB_PASSWORD="$DOCKERHUB_PASSWORD"
    - ./gradlew :telegram-stock-bot:clean build -x test -PDOCKERHUB_USERNAME="$DOCKERHUB_USERNAME" -PDOCKERHUB_PASSWORD="$DOCKERHUB_PASSWORD"
    - ./gradlew :tinkoff-stock-app:clean build -x test -PDOCKERHUB_USERNAME="$DOCKERHUB_USERNAME" -PDOCKERHUB_PASSWORD="$DOCKERHUB_PASSWORD"

assemble_job:
  stage: build
  only:
    - master
  allow_failure: false
  script:
    - ./gradlew :stock-app-statistic:assemble -PDOCKERHUB_USERNAME="$DOCKERHUB_USERNAME" -PDOCKERHUB_PASSWORD="$DOCKERHUB_PASSWORD"
    - ./gradlew :telegram-stock-bot:assemble -PDOCKERHUB_USERNAME="$DOCKERHUB_USERNAME" -PDOCKERHUB_PASSWORD="$DOCKERHUB_PASSWORD"
    - ./gradlew :tinkoff-stock-app:assemble -PDOCKERHUB_USERNAME="$DOCKERHUB_USERNAME" -PDOCKERHUB_PASSWORD="$DOCKERHUB_PASSWORD"
  # ToDo: разобраться с передачей *.jar-ников в push-to-docker-hub через artifacts/cache

push-to-docker-hub:
  stage: release
  only:
    - master
  allow_failure: false
  script:
    # jib.dependsOn(bootJar) in build.gradle
    - ./gradlew :stock-app-statistic:jib -PDOCKERHUB_USERNAME="$DOCKERHUB_USERNAME" -PDOCKERHUB_PASSWORD="$DOCKERHUB_PASSWORD"
    - ./gradlew :telegram-stock-bot:jib -PDOCKERHUB_USERNAME="$DOCKERHUB_USERNAME" -PDOCKERHUB_PASSWORD="$DOCKERHUB_PASSWORD" -PTELEGRAM_TOKEN="$TELEGRAM_TOKEN"
    - ./gradlew :tinkoff-stock-app:jib -PDOCKERHUB_USERNAME="$DOCKERHUB_USERNAME" -PDOCKERHUB_PASSWORD="$DOCKERHUB_PASSWORD" -PTINKOFF_TOKEN="$TINKOFF_TOKEN"

create-kind-cluster:
  stage: deploy
  only:
    - master
  allow_failure: false
  before_script:
    - check_kind_cluster=$(kind get clusters)
  script:
    - |-
      if [[ $check_kind_cluster == "kind" ]]; then
          echo "Кластер готов."
      else 
          kind create cluster --config=kubernetes/kind-config.yaml --kubeconfig $KUBECONFIG
      fi
  after_script:
    - kind get clusters

# ToDo: По хорошему нужно обновлять deployments через kubectl patch/set по id коммита,
# чтобы у каждого тэга docker-контейнера была версия с id коммита, но для демонстрации хватит.
deploy-in-kubernetes:
  stage: deploy
  only:
    - master
  allow_failure: true
  before_script:
    - cd kubernetes
    # ToDo:создать отдельный namespace для проверки перед деплоем
    - check_deployment=$(kubectl get deployment telegram-stock-bot --ignore-not-found=true)
    - echo $check_deployment
    - |-
      check_flannel=$(kubectl get all -n kube_flannel --ignore-not-found=true)
      if [ -z "${check_flannel}" ] ; then
          kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml 
      fi
  script:
    # ToDo: Упаковать все конфиги в Helm шаблоны
    - |-
      if [ -z "${check_deployment}" ] ; then
          echo "INIT"
          # Импорт общей конфигураций
          kubectl apply -f config/stock-app-config.yaml
          # Деплой kafka + zookeeper
          kubectl apply -f kafka/zookeeper.yaml
          kubectl apply -f kafka/kafka.yaml
          # Деплой PostgreSQL + PostGIS
          kubectl apply -f db/postgres-config.yaml
          kubectl apply -f db/storage_postgres.yaml
          kubectl apply -f db/postgres.yaml
          # Деплой микросервиса с подсчётом статистики
          kubectl apply -f stock-app-statistic/service_stock-app-stat.yaml
          kubectl apply -f stock-app-statistic/deploy_stock-app-stat.yaml
          # Деплой микросервиса с телеграм-ботом
          kubectl apply -f telegram-stock-bot/service_telegram-stock-bot.yaml
          kubectl apply -f telegram-stock-bot/deploy_telegram-stock-bot.yaml
          # Деплой микросервиса с tinkoff API
          kubectl apply -f tinkoff-stock-app/service_tinkoff-stock-app.yaml
          kubectl apply -f tinkoff-stock-app/ingress_tinkoff-stock-app.yaml
          kubectl apply -f tinkoff-stock-app/deploy_tinkoff-stock-app.yaml
      else 
          echo "UPDATE"
          # Импорт общей конфигураций
          kubectl apply -f config/stock-app-config.yaml
  
          # Деплой микросервиса с подсчётом статистики
          kubectl apply -f stock-app-statistic/service_stock-app-stat.yaml
          kubectl apply -f stock-app-statistic/deploy_stock-app-stat.yaml
          kubectl rollout restart deployment stock-app-stat
          # Деплой микросервиса с телеграм-ботом
          kubectl apply -f telegram-stock-bot/service_telegram-stock-bot.yaml
          kubectl apply -f telegram-stock-bot/deploy_telegram-stock-bot.yaml
          kubectl rollout restart deployment telegram-stock-bot
          # Деплой микросервиса с tinkoff API
          kubectl apply -f tinkoff-stock-app/service_tinkoff-stock-app.yaml
          kubectl apply -f tinkoff-stock-app/ingress_tinkoff-stock-app.yaml
          kubectl apply -f tinkoff-stock-app/deploy_tinkoff-stock-app.yaml
          kubectl rollout restart deployment tinkoff-stock-app
      fi
  after_script:
    # Проверка и установка INGRESS плагина (NGINX)
    - |-
      check_ing=$(kubectl get all -n ingress-nginx --ignore-not-found=true)
      if [ -z "${check_ing}" ] ; then
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
      else 
          kubectl get pods 
      fi
