stages:
  - docker-hub
  - kind-cluster
#   - deploy

build-job:
  stage: docker-hub
  script:
    - ./gradlew :stock-app-statistic:jib -PDOCKERHUB_USERNAME="$env:DOCKERHUB_USERNAME" -PDOCKERHUB_PASSWORD="$env:DOCKERHUB_PASSWORD"
    - ./gradlew :telegram-stock-bot:jib -PDOCKERHUB_USERNAME="$env:DOCKERHUB_USERNAME" -PDOCKERHUB_PASSWORD="$env:DOCKERHUB_PASSWORD" -PTELEGRAM_TOKEN="$env:TELEGRAM_TOKEN"
    - ./gradlew :telegram-stock-bot:jib -PDOCKERHUB_USERNAME="$env:DOCKERHUB_USERNAME" -PDOCKERHUB_PASSWORD="$env:DOCKERHUB_PASSWORD" -PTINKOFF_TOKEN="$env:TINKOFF_TOKEN"


create-kind-cluster:
  stage: kind-cluster
  script:
    - "kubectl cluster-info --context kind-kind"
    - "if [$message == 'error: context \"kind-kind\" does not exist' || $message == 'Error in configuration: context was not found for specified context: kind-kind' ]; then echo create-cluster; else echo continue; fi""

    #- kind create cluster --config=kubernetes/kind-config.yaml

# deploy-job:
#   stage: deploy
#   environment: production
#   script:
#     - echo "Deploying application..."
#     - echo "Application successfully deployed."
