apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-app-stat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-app-stat
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: stock-app-stat
    spec:
      containers:
        - image: devalurum/stock-app-stat:latest
          name: stock-app-stat
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: stock-app-config
          env:
            - name: DATABASE_HOST
              value: postgres
            - name: KAFKA_HOST
              value: kafka-service
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: 8092
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8092
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 2
            initialDelaySeconds: 15