---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: "stock_system"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "12345"
  ALLOW_IP_RANGE: "0.0.0.0/0"
