kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv4
  apiServerAddress: 127.0.0.1
  apiServerPort: 6444
  disableDefaultCNI: false
kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
        authorization-mode: "AlwaysAllow"
    ---
    apiVersion: kubelet.config.k8s.io/v1beta1
    kind: KubeletConfiguration
    metadata:
      name: config
    imageGCHighThresholdPercent: 90
    evictionHard:
      nodefs.available: "0%"
      nodefs.inodesFree: "0%"
      imagefs.available: "70%"
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 8880
        protocol: TCP
        listenAddress: 10.10.0.220
  - role: worker